// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_stage4 = "CgkIh_65hOUGEAIQBA"; // <GPGSID>
        public const string achievement_stage5 = "CgkIh_65hOUGEAIQBQ"; // <GPGSID>
        public const string achievement_stage6 = "CgkIh_65hOUGEAIQBg"; // <GPGSID>
        public const string achievement_stage7 = "CgkIh_65hOUGEAIQBw"; // <GPGSID>
        public const string leaderboard_score = "CgkIh_65hOUGEAIQCA"; // <GPGSID>
        public const string achievement_stage1 = "CgkIh_65hOUGEAIQAQ"; // <GPGSID>
        public const string achievement_stage2 = "CgkIh_65hOUGEAIQAg"; // <GPGSID>
        public const string achievement_stage3 = "CgkIh_65hOUGEAIQAw"; // <GPGSID>

}

